server:
  port: 8080
#  servlet:
#    context-path: /blog

spring:
  profiles:
    active: dev

  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #==================================================#
  #================ Database Setting ================#
  #==================================================#
  datasource:
    dbcp2:
      min-idle: 1 #????????????????С?
      max-total: 20
      initial-size: 1 #????????????????????????????????
      max-wait-millis: 60000
      validation-query: SELECT 1 #???????????????У???sql??????
      test-on-borrow: false #????????????????????????
      test-while-idle: true #?????????????????????????
      time-between-eviction-runs-millis: 60000 #????????????顢??????????????????????С????????????????
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
aliyun:
  param:
    sms:
      accessKeyId: ***********
      accessSecret: ***********